In [1]:
import numpy as np

data = np.random.randint(10, size=(10,8))

print(data)

[[6 1 7 7 9 6 7 2]
 [0 4 3 4 0 6 9 9]
 [7 1 3 7 1 1 6 7]
 [4 8 9 4 9 1 4 8]
 [1 4 2 2 4 9 6 8]
 [6 1 0 7 6 1 6 9]
 [7 4 3 1 0 0 1 5]
 [9 5 3 2 6 4 1 9]
 [5 6 6 8 0 4 9 3]
 [9 8 0 4 7 5 1 3]]
