In [2]:
import numpy as np

data = np.random.randint(10, size=(10,8))

print(data)

[[2 6 9 8 2 6 5 9]
 [7 0 1 9 6 2 5 0]
 [7 2 3 2 6 4 0 5]
 [0 5 5 4 0 5 0 9]
 [1 9 3 2 3 0 8 8]
 [4 6 6 1 7 2 4 8]
 [9 8 2 2 5 2 7 0]
 [8 6 4 2 0 1 2 5]
 [0 4 1 8 4 3 3 2]
 [5 1 5 8 5 2 0 7]]
